Remove broken imports
These imports were unused and caused the compilation to fail

The error message was:
:core:compileJava
warning: Supported source version 'RELEASE_6' from annotation processor 'org.antlr.v4.runtime.misc.NullUsageProcessor' less than -source '1.8'
/home/keszocze/proggs/BioViz/core/src/de/bioviz/ui/DrawableSprite.java:16: error: package javafx.scene does not exist
import javafx.scene.Parent;
                   ^
1 error
1 warning
:core:compileJava FAILED

FAILURE: Build failed with an exception.